[package]
name = "subcon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde-saphyr = "0.0.11"
serde_json = "1.0.145"
serde_yaml = "0.9.34"
