[[groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
rule = [
  "[]ğŸŒ äºšæ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[groups]]
interval = 120
name = "ğŸ  å®¶åº­å®½å¸¦"
rule = ["(å®¶|å®¶å®½)"]
type = "select"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸŒ äºšæ´²èŠ‚ç‚¹"
rule = ["(?!.*å®¶å®½)(é¦™æ¸¯|HK|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|æ–°åŠ å¡|ç‹®åŸ|SG|é©¬æ¥è¥¿äºš|è¶Šå—)"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
rule = ["(?!.*å®¶å®½)(é¦™æ¸¯|HK)"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
rule = ["(?!.*å®¶å®½)(æ–°åŠ å¡|ç‹®åŸ|SG)"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸ‘Š å°æ¹¾èŠ‚ç‚¹"
rule = ["(?!.*å®¶å®½)(å°æ¹¾|TW)"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
rule = ["(?!.*å®¶å®½)(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
rule = [
  "(?!.*å®¶å®½)(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)",
]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
interval = 120
name = "ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹"
rule = ["(?!.*å®¶å®½)(è‹±å›½|å¾·å›½|è·å…°)"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[groups]]
name = "âœ… å›½å†…æœåŠ¡"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]
type = "select"

[[groups]]
name = "âš ï¸ åŒºåŸŸé™åˆ¶"
rule = [
  "[]ğŸ  å®¶åº­å®½å¸¦",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[groups]]
name = "ğŸ§² AI Service"
rule = [
  "[]ğŸ  å®¶åº­å®½å¸¦",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[groups]]
name = "ğŸ¬ æ¸¯æ¾³æµåª’ä½“"
rule = ["[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹", "[]ğŸ  å®¶åº­å®½å¸¦", "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "(æ¾³é—¨|MO)"]
type = "select"

[[groups]]
name = "ğŸ¬ å°æ¹¾æµåª’ä½“"
rule = ["[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹", "[]ğŸ  å®¶åº­å®½å¸¦", "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "(å°æ¹¾|TW)"]
type = "select"

[[groups]]
name = "ğŸ¬ æ—¥æœ¬æµåª’ä½“"
rule = [
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ  å®¶åº­å®½å¸¦",
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ¯ å…¨çƒç›´è¿",
  "(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)",
]
type = "select"

[[groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
rule = [
  "[]ğŸ¯ å…¨çƒç›´è¿",
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  ".*",
]
type = "select"

[[groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
rule = [
  "[]ğŸ¯ å…¨çƒç›´è¿",
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  ".*",
]
type = "select"

[[groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
rule = ["[]DIRECT", "[]REJECT", ".*"]
type = "select"

[[groups]]
name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
rule = [
  "[]REJECT",
  "[]DIRECT",
  "[]ğŸ¯ å…¨çƒç›´è¿",
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  ".*",
]
type = "select"

[[groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
rule = [
  "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
  "[]ğŸ‡ªğŸ‡º æ¬§æ´²èŠ‚ç‚¹",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
  "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
  "[]ğŸ‘Š å°æ¹¾èŠ‚ç‚¹",
  "[]ğŸ¯ å…¨çƒç›´è¿",
  "[]REJECT",
]
type = "select"
