[[rulesets]]
group = "ğŸ§² AI Service"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/ai.txt",
  "https://ruleset.skk.moe/Clash/non_ip/apple_intelligence.txt",
]

[[rulesets]]
group = "ğŸ¬ æ¸¯æ¾³æµåª’ä½“"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/stream_hk.txt",
  "https://ruleset.skk.moe/Clash/ip/stream_hk.txt",
  "https://ruleset.skk.moe/Clash/non_ip/stream_biliintl.txt",
  "https://ruleset.skk.moe/Clash/ip/stream_biliintl.txt",
]

[[rulesets]]
group = "ğŸ¬ å°æ¹¾æµåª’ä½“"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/stream_tw.txt",
  "https://ruleset.skk.moe/Clash/ip/stream_tw.txt",
]

[[rulesets]]
group = "ğŸ¬ æ—¥æœ¬æµåª’ä½“"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/stream_jp.txt",
  "https://ruleset.skk.moe/Clash/ip/stream_jp.txt",
]

[[rulesets]]
group = "âš ï¸ åŒºåŸŸé™åˆ¶"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/stream.txt",
  "https://ruleset.skk.moe/Clash/ip/stream.txt",
]

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/apple_services.txt",
  "https://ruleset.skk.moe/Clash/ip/apple_services.txt",
  "https://ruleset.skk.moe/Clash/non_ip/apple_cdn.txt",
  "https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt",
]

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/microsoft.txt",
  "https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt",
]

[[rulesets]]
group = "âœ… å›½å†…æœåŠ¡"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/domestic.txt",
  "https://ruleset.skk.moe/Clash/ip/domestic.txt",
  "https://ruleset.skk.moe/Clash/non_ip/neteasemusic.txt",
  "https://ruleset.skk.moe/Clash/ip/neteasemusic.txt",
  "https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt",
]

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = [
  "[]GEOIP,CN",
  "https://ruleset.skk.moe/Clash/non_ip/direct.txt",
  "https://ruleset.skk.moe/Clash/non_ip/lan.txt",
  "https://ruleset.skk.moe/Clash/ip/lan.txt",
  "https://ruleset.skk.moe/Clash/non_ip/cdn.txt",
  "https://ruleset.skk.moe/Clash/ip/cdn.txt",

]

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/global.txt",
  "https://ruleset.skk.moe/Clash/non_ip/global_plus.txt",
  "https://ruleset.skk.moe/Clash/non_ip/telegram.txt",
  "https://ruleset.skk.moe/Clash/ip/telegram.txt",
  "https://ruleset.skk.moe/Clash/ip/telegram_asn.txt",
  "https://ruleset.skk.moe/Clash/non_ip/my_proxy.txt",
  "https://ruleset.skk.moe/Clash/non_ip/my_plus.txt",
  "https://ruleset.skk.moe/Clash/non_ip/gitlab.txt",
  "https://ruleset.skk.moe/Clash/non_ip/my_git.txt",
]

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = [
  "https://ruleset.skk.moe/Clash/non_ip/reject.txt",
  "https://ruleset.skk.moe/Clash/ip/reject.txt",
  "https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt",
  "https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt",
  "https://ruleset.skk.moe/Clash/non_ip/reject-url-regex.txt",
  "https://ruleset.skk.moe/Clash/non_ip/my_reject.txt",
]

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = ["[]FINAL"]
